name: app_builder_repository
description: Dart package which manages the product domain.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  appcheap_flutter_core:
    path: ../../appcheap_flutter_core
  html_unescape: ^2.0.0
  json_annotation: ^4.7.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0