name: wc_appointment_repository
description: Dart package which manages the product domain.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  appcheap_flutter_core:
    path: ../../appcheap_flutter_core

dev_dependencies:
  flutter_lints: ^2.0.0